import { ChannelSchedule, Channel } from '../types';

export const fallbackChannels: Channel[] = [
  { id: 'rai-1', name: 'Rai 1', number: 1, logo: 'https://images.services.rai.it/image/rai1.png' },
  { id: 'rai-2', name: 'Rai 2', number: 2, logo: 'https://images.services.rai.it/image/rai2.png' },
  { id: 'rai-3', name: 'Rai 3', number: 3, logo: 'https://images.services.rai.it/image/rai3.png' },
  { id: 'rete-4', name: 'Rete 4', number: 4, logo: 'https://static3.mediasetplay.mediaset.it/brand/rete4.png' },
  { id: 'canale-5', name: 'Canale 5', number: 5, logo: 'https://static3.mediasetplay.mediaset.it/brand/canale5.png' },
  { id: 'italia-1', name: 'Italia 1', number: 6, logo: 'https://static3.mediasetplay.mediaset.it/brand/italia1.png' },
  { id: 'la7', name: 'La7', number: 7, logo: 'https://www.la7.it/assets/images/la7_logo.png' },
  { id: 'tv8', name: 'TV8', number: 8, logo: 'https://images.ctfassets.net/tv8.png' },
  { id: 'nove', name: 'Nove', number: 9, logo: 'https://nove.tv/assets/nove.png' },
  { id: '20', name: '20 Mediaset', number: 20, logo: 'https://static3.mediasetplay.mediaset.it/brand/20.png' },
  { id: 'rai-4', name: 'Rai 4', number: 21, logo: 'https://images.services.rai.it/image/rai4.png' },
  { id: 'iris', name: 'Iris', number: 22, logo: 'https://static3.mediasetplay.mediaset.it/brand/iris.png' },
  { id: 'rai-movie', name: 'Rai Movie', number: 24, logo: 'https://images.services.rai.it/image/raimovie.png' },
  { id: 'cine34', name: 'Cine34', number: 34, logo: 'https://static3.mediasetplay.mediaset.it/brand/cine34.png' },
  { id: 'focus', name: 'Focus', number: 35, logo: 'https://static3.mediasetplay.mediaset.it/brand/focus.png' },
  { id: 'giallo', name: 'Giallo', number: 38, logo: 'https://giallotv.it/assets/giallo.png' },
  { id: 'top-crime', name: 'Top Crime', number: 39, logo: 'https://static3.mediasetplay.mediaset.it/brand/topcrime.png' },
  { id: 'dmax', name: 'DMAX', number: 52, logo: 'https://dmax.it/assets/dmax.png' },
  { id: 'tele-norba', name: 'Tele Norba', number: 10, logo: 'https://portiamovalore.uniba.it/uploads/loghi/Logo%20telenorba_1579780216.png' },
  { id: 'radionorba-tv', name: 'Radionorba TV', number: 19, logo: 'https://static.radionorba.it/radionorba-tv.png' },
  { id: 'trm-h24', name: 'TRM h24', number: 16, logo: 'https://iptv-epg.org/images/ZULCXWIuxOovobn-tvYaeKu__sW5MyaXR2ep6pgbkAVFBqHxajlUg1RJkLyYPB6EtPCisdbrk4drDv7Fc_uFyYFF8e1Ngag9uwvaU_L6' },
  { id: 'inter-tv', name: 'Inter TV', number: 232, logo: 'https://iptv-epg.org/images/intertv.png' },
  { id: 'milan-tv', name: 'Milan TV', number: 230, logo: 'https://iptv-epg.org/images/milantv.png' },
];

export const fallbackStaseraSchedule: ChannelSchedule[] = [
  {
    channel: {
      id: 'rai-1',
      name: 'Rai 1',
      number: 1,
      logo: 'https://images.services.rai.it/image/rai1.png',
      streamUrl: 'https://www.raiplay.it/dirette/rai1',
      streamLabel: 'RaiPlay',
    },
    programs: [
      {
        id: '101',
        title: 'Affari Tuoi',
        description: 'Il celebre gioco dei pacchi condotto da Stefano De Martino.',
        category: 'Intrattenimento',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
        startTimeFormatted: '20:35',
        endTimeFormatted: '21:30',
        posterUrl: 'https://images.services.rai.it/image/affari-tuoi.jpg',
        isPrimaSerata: true,
      },
      {
        id: '102',
        title: 'Ulisse: Il piacere della scoperta',
        description: 'Alberto Angela ci guida in un viaggio affascinante attraverso la storia e la cultura.',
        category: 'Documentari',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 5.5).toISOString(),
        startTimeFormatted: '21:30',
        endTimeFormatted: '23:45',
        posterUrl: 'https://images.services.rai.it/image/ulisse.jpg',
        isPrimaSerata: false,
        isSecondaSerata: true,
      },
    ],
  },
  {
    channel: {
      id: 'canale-5',
      name: 'Canale 5',
      number: 5,
      logo: 'https://static3.mediasetplay.mediaset.it/brand/canale5.png',
      streamUrl: 'https://mediasetinfinity.mediaset.it/diretta/canale5_cC5',
      streamLabel: 'Mediaset Infinity',
    },
    programs: [
      {
        id: '201',
        title: 'Striscia la Notizia',
        description: 'La voce della presenza e del dissenso con i conduttori e i servizi degli inviati.',
        category: 'Intrattenimento',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
        startTimeFormatted: '20:40',
        endTimeFormatted: '21:35',
        posterUrl: 'https://static3.mediasetplay.mediaset.it/brand/striscia.jpg',
        isPrimaSerata: true,
      },
      {
        id: '202',
        title: 'Il Gladiatore',
        description: 'Capolavoro di Ridley Scott con Russell Crowe e Joaquin Phoenix. Un generale romano tradito cerca vendetta.',
        category: 'Film',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
        startTimeFormatted: '21:35',
        endTimeFormatted: '00:15',
        posterUrl: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
        isPrimaSerata: false,
        isSecondaSerata: true,
      },
    ],
  },
  {
    channel: {
      id: 'italia-1',
      name: 'Italia 1',
      number: 6,
      logo: 'https://static3.mediasetplay.mediaset.it/brand/italia1.png',
      streamUrl: 'https://mediasetinfinity.mediaset.it/diretta/italia1_cI1',
      streamLabel: 'Mediaset Infinity',
    },
    programs: [
      {
        id: '301',
        title: 'Le Iene Show',
        description: 'Inchieste giornalistiche, servizi d\'attualità e interviste con il team delle Iene.',
        category: 'Intrattenimento',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 2.5).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 6.5).toISOString(),
        startTimeFormatted: '21:20',
        endTimeFormatted: '01:00',
        posterUrl: 'https://static3.mediasetplay.mediaset.it/brand/iene.jpg',
        isPrimaSerata: true,
      },
    ],
  },
  {
    channel: {
      id: 'la7',
      name: 'La7',
      number: 7,
      logo: 'https://www.la7.it/assets/images/la7_logo.png',
      streamUrl: 'https://www.la7.it/dirette-tv',
      streamLabel: 'La7',
    },
    programs: [
      {
        id: '401',
        title: 'Otto e Mezzo',
        description: 'Approfondimento politico e di attualità condotto da Lilli Gruber con ospiti in studio.',
        category: 'Informazione',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 2.8).toISOString(),
        startTimeFormatted: '20:30',
        endTimeFormatted: '21:15',
        posterUrl: 'https://www.la7.it/assets/images/ottoemezzo.jpg',
        isPrimaSerata: true,
      },
      {
        id: '402',
        title: 'PiazzaPulita',
        description: 'Il programma di approfondimento e inchiesta condotto da Corrado Formigli.',
        category: 'Informazione',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 2.8).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 6.5).toISOString(),
        startTimeFormatted: '21:15',
        endTimeFormatted: '00:45',
        posterUrl: 'https://www.la7.it/assets/images/piazzapulita.jpg',
        isPrimaSerata: false,
        isSecondaSerata: true,
      },
    ],
  },
  {
    channel: {
      id: '20',
      name: '20 Mediaset',
      number: 20,
      logo: 'https://static3.mediasetplay.mediaset.it/brand/20.png',
      streamUrl: 'https://mediasetinfinity.mediaset.it/diretta/20_cVE',
      streamLabel: 'Mediaset Infinity',
    },
    programs: [
      {
        id: '501',
        title: 'UEFA Champions League Magazine',
        description: 'Tutti i gol, gli highlights e le interviste esclusive della massima competizione europea.',
        category: 'Sport',
        startTime: new Date(Date.now() + 1000 * 60 * 60 * 2.5).toISOString(),
        endTime: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
        startTimeFormatted: '21:00',
        endTimeFormatted: '23:30',
        posterUrl: 'https://image.tmdb.org/t/p/w500/football_champions.jpg',
        isPrimaSerata: true,
      },
    ],
  },
];
